//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Model {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Traduzioni {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traduzioni() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olive.Model.Traduzioni", typeof(Traduzioni).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Olive app v1.0.
        /// </summary>
        internal static string About_heading {
            get {
                return ResourceManager.GetString("About_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Olive app, made by Carlo Camagni &amp; Davide Motti.
        ///Olive is developed in C# and Xamarin, for source code visit http://gitlab.consortech.it:8080/explore/projects.
        ///You are free to download, modify, destroy or improve it.
        ///Thanks to Material Design Icons (https://materialdesignicons.com/) for in app icons, Pixabay (https://pixabay.com/it/) for menu background, Smashicons on Flaticon (https://www.flaticon.com/authors/smashicons) for the app icon.
        ///And to my daughter Olivia, this app is for you &lt;3..
        /// </summary>
        internal static string About_text {
            get {
                return ResourceManager.GetString("About_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open.
        /// </summary>
        internal static string HomePage_Button1 {
            get {
                return ResourceManager.GetString("HomePage_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error in settings, go to settings page.
        /// </summary>
        internal static string HomePage_buttonError {
            get {
                return ResourceManager.GetString("HomePage_buttonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error reaching Mobotix url, update urls in setting page..
        /// </summary>
        internal static string HomePage_dnsError {
            get {
                return ResourceManager.GetString("HomePage_dnsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tap button to call your Mobotix cam. If you have issue check the values in settings page..
        /// </summary>
        internal static string HomePage_Label1 {
            get {
                return ResourceManager.GetString("HomePage_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done on  {0}.
        /// </summary>
        internal static string HomePage_success {
            get {
                return ResourceManager.GetString("HomePage_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose a language.
        /// </summary>
        internal static string Language_pickerTitle {
            get {
                return ResourceManager.GetString("Language_pickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string Language_save {
            get {
                return ResourceManager.GetString("Language_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Making some stuff... | Round one, fight! |Tthese aren&apos;t the droids you&apos;re looking for | That is why you fail.|Adventure. Excitement. A Jedi craves not these things|Wars not make one great. | Do. Or do not. There is no try.| Always two there are, no more, no less. A master and an apprentice.|You fail because you don’t believe..
        /// </summary>
        internal static string Loading_message {
            get {
                return ResourceManager.GetString("Loading_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        internal static string MasterAbout {
            get {
                return ResourceManager.GetString("MasterAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        internal static string MasterLanguage {
            get {
                return ResourceManager.GetString("MasterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main Page.
        /// </summary>
        internal static string MasterMain {
            get {
                return ResourceManager.GetString("MasterMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string MasterSettings {
            get {
                return ResourceManager.GetString("MasterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string Setting_confirm_no {
            get {
                return ResourceManager.GetString("Setting_confirm_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string Setting_confirm_yes {
            get {
                return ResourceManager.GetString("Setting_confirm_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure to delete all entry?.
        /// </summary>
        internal static string Setting_confirmMessage {
            get {
                return ResourceManager.GetString("Setting_confirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete all entry.
        /// </summary>
        internal static string Settings_DelSettingsText {
            get {
                return ResourceManager.GetString("Settings_DelSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert settings in the form below. At least one reachable address (internal or external) is required.
        /// </summary>
        internal static string Settings_Description {
            get {
                return ResourceManager.GetString("Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Url must start with http or https.
        /// </summary>
        internal static string Settings_httpvalidation {
            get {
                return ResourceManager.GetString("Settings_httpvalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a External IP address or domain.
        /// </summary>
        internal static string Settings_ipextPH {
            get {
                return ResourceManager.GetString("Settings_ipextPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Internal IP address or domain.
        /// </summary>
        internal static string Settings_ipPH {
            get {
                return ResourceManager.GetString("Settings_ipPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your Password.
        /// </summary>
        internal static string Settings_passPH {
            get {
                return ResourceManager.GetString("Settings_passPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One or more settings are invalid.
        /// </summary>
        internal static string Settings_SaveSetKo {
            get {
                return ResourceManager.GetString("Settings_SaveSetKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All settings saved.
        /// </summary>
        internal static string Settings_SaveSetOk {
            get {
                return ResourceManager.GetString("Settings_SaveSetOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string Settings_SaveSettingsText {
            get {
                return ResourceManager.GetString("Settings_SaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your Username.
        /// </summary>
        internal static string Settings_userPH {
            get {
                return ResourceManager.GetString("Settings_userPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Entry {0} is not properly formatted.
        /// </summary>
        internal static string Settings_validationError {
            get {
                return ResourceManager.GetString("Settings_validationError", resourceCulture);
            }
        }
    }
}
